### PR TITLE
Fix downloading files, SR exporting and other bugs

### LINKED ISSUE #926: Downloading files is broken
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Download a Scan Report, or rules does not work.

### Expected Behavior

_No response_

### Steps To Reproduce

Upload a scan report
Try to download it

### Environment

```markdown
- OS:
- Other environment details:
```

### I'm part of a Project Team

_No response_

### Anything else?

The code to download files would previously link directly to the API that would allow for the file to be downloaded - the endpoint was hardcoded in the html.
This no longer works as the url has changed, but additionally won't work as the user client won't be authenticated to download it.
Effectively the Next js server is authenticated, and needs to download the file and return to the browser

### Are you willing to contribute to resolve this issue?

✅ Yes, me or my team intend to do the development.

### PR DESCRIPTION
**Pull request by AndrewThien**
# Changes

This PR fixes the process of downloading files and ScanReport exporting in Carrot as well as other bugs that may have been caused by separating the Front end from the Back End. 

This PR also add the Export Poetry Plugin to the DockerFiles and workflows.

Closes #926

### CODE REVIEW

**Review by MoizIqbal97 — DISMISSED** [review]

File: app/next-client-app/app/(protected)/scanreports/[id]/downloads/columns.tsx [hunk 1]
```diff
@@ -82,15 +84,32 @@ export const columns: ColumnDef<FileDownload>[] = [
     id: "Download",
     header: ({ column }) => <DataTableColumnHeader column={column} title="" />,
     cell: ({ row }) => {
-      const { id, scan_report } = row.original;
+      const { id, scan_report, file_type, name } = row.original;
+      const handleDownload = async () => {
+        const response = await downloadFile(scan_report, id, file_type.value);
```
Comment (Jivanam) [inline app/next-client-app/app/(protected)/scanreports/[id]/downloads/columns.tsx:89]: Can we call `downloadFiles` which I believe is server method from the client component?

**Review by Jivanam — DISMISSED** [review]

File: app/next-client-app/app/(protected)/scanreports/[id]/downloads/columns.tsx [hunk 2]
```diff
@@ -82,15 +84,32 @@ export const columns: ColumnDef<FileDownload>[] = [
     id: "Download",
     header: ({ column }) => <DataTableColumnHeader column={column} title="" />,
     cell: ({ row }) => {
-      const { id, scan_report } = row.original;
+      const { id, scan_report, file_type, name } = row.original;
+      const handleDownload = async () => {
```
Comment (AndyRae) [inline app/next-client-app/app/(protected)/scanreports/[id]/downloads/columns.tsx:88]: This fixes the `downloads` page, but not the `Export Scan Report` though right?

Comment (AndrewThien) [reply app/next-client-app/app/(protected)/scanreports/[id]/downloads/columns.tsx:88]: yes, I forgot about that. Let me fix that in this PR as well. Thanks!

**Review by Jivanam — APPROVED** [review]
