### PR TITLE
Fix/717/click row to redirect

### LINKED ISSUE #717: 🐛 Unable to access scan reports list within a dataset
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, in the previous mapper version when we clicked the dataset name it would take us to a page with all scan reports associated with that dataset. Now it does nothing, though the hand cursor appears over it. Is this feature intentionally removed? or will become available in future?

### Expected Behavior

Show the scan reports associated with that particular dataset. 

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Other environment details:
```

### I'm part of a Project Team

_No response_

### Anything else?

_No response_

### Are you willing to contribute to resolve this issue?

None

### PR DESCRIPTION
**Pull request by Dev-Akashili**
# Changes

This fixes the bug where clicking on some parts of a row to link to another page not working and also the error in the URL builder when trying to link to another page. Closes #717

### CODE REVIEW

**Review by AndyRae — APPROVED** [review]

**Review by AndrewThien — APPROVED** [review]

File: app/next-client-app/components/data-table/index.tsx [hunk 1]
```diff
@@ -68,6 +68,14 @@ export function DataTable<TData, TValue>({
     },
   });
 
+  const handleRowClick = (id: string) => {
+    const location = window.location.pathname;
+    window.location.href = UrlBuider(
```
Comment (spco) [inline app/next-client-app/components/data-table/index.tsx:73]: Not for now, but can we please correct the spelling of `UrlBuider` here and in its definition above?
