### PR TITLE
Fix undefined client request unavailable data

### LINKED ISSUE #1088: NextJS client request unavailable data
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When the person ID and the date event in a table are not set, users access the `update table` page, Next will "blindly" try to get the PersonID and DateEvent fields of that table, which are not available yet. This causes the error:  `Not Found: /api/v2/scanreports/7/tables/19/fields/undefined/`, for example, from API.

### Expected Behavior

Next client is supposed to check if `table.person_id` / `table.date_event` is available first before making the calls. See lines `40-41` of `app/(protected)/scanreports/[id]/tables/[tableId]/update/page.tsx`

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS:
- Other environment details:
```

### I'm part of a Project Team

_No response_

### Anything else?

_No response_

### Are you willing to contribute to resolve this issue?

✅ Yes, me or my team intend to do the development.

### PR DESCRIPTION
**Pull request by brian-kim31**
🦋 Bug Fix

## PR Description
When users access the update table page for tables where Person ID and Date Event fields are not set, the Next.js client was making API calls with undefined field IDs, causing 404 errors and console warnings.

## Solution:
Added proper field existence checks before making API calls. Instead of blindly calling getScanReportField(id, tableId, table.person_id?.id), the code now checks if table.person_id?.id exists first. When fields don't exist, a default field object is used instead of making API calls with undefined values.

## Related Issues or other material
Related #1088
Closes #1088

## Screenshots, example outputs/behaviour etc.
Screenshot 2025-07-30 at 12 15 45
Screenshot 2025-07-30 at 12 16 35

### CODE REVIEW

File: app/next-client-app/app/(protected)/scanreports/[id]/tables/[tableId]/update/page.tsx [hunk 1]
```diff
@@ -37,8 +37,38 @@ export default async function UpdateTable(props: UpdateTableProps) {
   const scanReportsFields = await getAllScanReportFields(id, tableId, query);
 
   const table = await getScanReportTable(id, tableId);
-  const personId = await getScanReportField(id, tableId, table.person_id?.id);
-  const dateEvent = await getScanReportField(id, tableId, table.date_event?.id);
+
+  // Check if fields are available first before making the calls
+  const defaultField = {
```
Comment (AndrewThien) [inline app/next-client-app/app/(protected)/scanreports/[id]/tables/[tableId]/update/page.tsx:42]: Is there any better names than `defaultField`?

Comment (brian-kim31) [reply app/next-client-app/app/(protected)/scanreports/[id]/tables/[tableId]/update/page.tsx:42]: maybe fallbackField, What do you think? Its more descriptive

**Review by AndyRae — APPROVED** [review]
